version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - CI=false
        - NODE_VERSION=20
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
